### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by shamoons** [mpariente/pytorch_stoi#6]
I keep getting this, not sure why

**Comment by mpariente** [comment]
Full traceback?

**Comment by shamoons** [comment]
```
Traceback (most recent call last):
  File "/home/shamoon/speech-reconstruction/train_transformer_encoder.py", line 208, in <module>
    main()
  File "/home/shamoon/speech-reconstruction/train_transformer_encoder.py", line 133, in main
    train_loss = train(reconstruct_spect_model, optimizer=optimizer, dataset=train_loader)
  File "/home/shamoon/speech-reconstruction/train_transformer_encoder.py", line 197, in train
    loss = model.loss_fn(pred, ground_truth)
  File "/home/shamoon/speech-reconstruction/models/transformer_reconstruct.py", line 65, in loss_fn
    stoi_loss = NegSTOILoss(sample_rate=16000)(pred_flat, truth_flat)
  File "/home/shamoon/venvs/speech-reconstruction/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shamoon/venvs/speech-reconstruction/lib/python3.9/site-packages/torch_stoi/stoi.py", line 124, in forward
    x_spec = self.stft(targets, self.win, self.nfft, overlap=2)
  File "/home/shamoon/venvs/speech-reconstruction/lib/python3.9/site-packages/torch_stoi/stoi.py", line 214, in stft
    return torch.stft(x_padded, fft_size, hop_length=hop, window=win,
  File "/home/shamoon/venvs/speech-reconstruction/lib/python3.9/site-packages/torch/functional.py", line 515, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by mpariente** [comment]
The loss and the input tensor are on the same device?

**Comment by mpariente** [comment]
e.g. GPU?

**Comment by shamoons** [comment]
That's right - same device:

```

    def loss_fn(self, pred, truth):
        truth_flat = torch.reshape(truth, (truth.size(0),-1)).to(truth.device)
        pred_flat = torch.reshape(pred, (pred.size(0),-1)).to(truth.device)

        stoi_loss = NegSTOILoss(sample_rate=16000)(pred_flat, truth_flat)
        print('truth', truth.size(), truth_flat.size(), stoi_loss)
```

**Comment by mpariente** [comment]
The loss is not on the device. 
The loss is a nn.Module, and needs to be manipulated as such.

**Comment by shamoons** [comment]
I'm not sure I follow.. I have:
```
        x = x.to(DEVICE)
        y = y.to(DEVICE)
        ground_truth = y

        pred = model(x)

        loss = model.loss_fn(pred, ground_truth)
        loss.backward()
```

where the model loss_fn is what I [have here](https://github.com/mpariente/pytorch_stoi/issues/6#issuecomment-804947486)

**Comment by mpariente** [comment]
```python
stoi_loss = NegSTOILoss(sample_rate=16000)
stoi_loss = stoi_loss.to(device)
...
```
It instantiates a window, that lives on a device, so you need to move it. 

By the way, you should create it once and for all, not creating it every time, it's less efficient.

**Comment by shamoons** [comment]
You mean something like this?

```
        truth_flat = torch.reshape(truth, (truth.size(0), -1)).to(truth.device)
        pred_flat = torch.reshape(pred, (pred.size(0), -1)).to(truth.device)

        stoi_loss = NegSTOILoss(sample_rate=16000).to(truth.device)

        stoi_loss = stoi_loss(pred_flat, truth_flat)
```

**Comment by mpariente** [comment]
Yes, but you shouldn't recreate the object (`NegSTOILoss(sample_rate=16000)`) every time IMO.

Anyway, does this work with the current fix?

**Comment by shamoons** [comment]
Yes - seems to have solved it. One more question - it seems that the loss is negative. So do I want to do `1 - stoi_loss`?

**Comment by mpariente** [comment]
STOI: the higher, the better
NegStoi: -STOI, the lower the better. 

And we tend to minimize loss functions, so minimizing NegStoi will maximize STOI. 

Long story short, use NegSTOI as your loss.
